#! /bin/sh
#
# $Id$ 
#

set -e

configfile='/etc/guifi-proxy3/config.sh';
tmpfile=`/bin/tempfile -m 644`;

case $1 in
	configure|reconfigure)

	. /usr/share/debconf/confmodule
	db_version 2.0 || [ $? -lt 30 ]

	db_get guifi-proxy3/baseurl
	base_url=$RET
	db_get guifi-proxy3/node
	node=$RET
	db_get guifi-proxy3/forcefetch
	forcefetch=$RET


	/bin/cat << EOT > $tmpfile

#!/bin/sh
#
# Script at /usr/share/guifi-proxy3
#
# Server base url ex: http://www.guifi.net
base_url='$base_url';
# Node ID
node=$node;

EOT

	/usr/bin/ucf --three-way --debconf-ok $tmpfile $configfile
	/bin/rm $tmpfile

	if [ $forcefetch ]
	then
		echo "Fetching passwd file.";
		if [ -x /usr/share/guifi-proxy3/guifi-proxy3.sh ]; then echo "..."; /usr/share/guifi-proxy3/guifi-proxy3.sh; fi
	fi
	# Force logrotate
	touch /var/log/guifi-proxy3/guifi-proxy3.log
	/usr/sbin/logrotate -f /etc/logrotate.d/guifi-proxy3

        # save old config
	if [ -e "/etc/squid3/squid.conf" ]; then
		echo "Saving a copy of the current squid.conf ........ ...... squid.conf.backup.initial";
                /bin/cp -ax /etc/squid3/squid.conf /etc/squid3/squid.conf.backup.initial
        fi
        ## include name of server proxy in /etc/squid3/squid.conf
	db_get guifi-proxy3/proxy_name
	proxy_name$RET
	echo "auth_param basic realm `proxy_name` Squid proxy-caching web server " >> /etc/squid3/guifi.conf
	## include hosts lan allow with administrator of squid server
	db_get guifi-proxy3/allow_host
	allow_host=$RET
	if [allow_host]; then
		echo "acl to_privada_allow dst `allow_host`" >> /etc/squid3/guifi.conf
		echo "http_access allow to_privada_allow" >> /etc/squid3/guifi.conf
	fi
         
        
	echo "Loading special version Guifi.net ";
        /bin/echo "include /etc/squid3/guifi.conf" >> /etc/squid3/squid.conf
	/etc/init.d/squid3 restart
	exit 1
	;;

	*)
	echo "postinst called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac



exit 0
