#!/bin/bash
#
/bin/echo "" >> /var/log/squid3/netejar_cache.log
/bin/echo "`date +%y-%m-%d___%k:%M`-----------------------------------------------------------------------------------" >> /var/log/squid3/netejar_cache.log
/usr/sbin/invoke-rc.d squid3 stop >> /var/log/squid3/netejar_cache.log
/bin/rm -Rf /var/spool/squid3/* >> /var/log/squid3/netejar_cache.log
/usr/sbin/squid3 squid3 -z >> /var/log/squid3/netejar_cache.log
/usr/sbin/invoke-rc.d squid3 start >> /var/log/squid3/netejar_cache.log
#fi

