Document: guifi-proxy
Title: Debian guifi-proxy Manual
Author: <insert document author here>
Abstract: This manual describes what guifi-proxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/guifi-proxy/guifi-proxy.sgml.gz

Format: postscript
Files: /usr/share/doc/guifi-proxy/guifi-proxy.ps.gz

Format: text
Files: /usr/share/doc/guifi-proxy/guifi-proxy.text.gz

Format: HTML
Index: /usr/share/doc/guifi-proxy/html/index.html
Files: /usr/share/doc/guifi-proxy/html/*.html

  
