#!/bin/sh
#
# $Id$
#

set -e

case $1 in
	configure|reconfigure)

	. /usr/share/debconf/confmodule
	db_version 2.0 || [ $? -lt 30 ]
	#
	db_get guifi-proxy3/baseurl
	base_url=$RET
	db_get guifi-proxy3/node
	node=$RET
	#first ldap server
	db_get guifi-proxy3/ldap_main
	ldap_main=$RET
	# second and backup ldap server
	db_get guifi-proxy3/ldap_backup
	ldap_backup=$RET
        ## include name of server proxy in /etc/squid3/squid.conf
	db_get guifi-proxy3/proxy_name
	proxy_name=$RET
	# admin email
	db_get guifi-proxy3/email
        email=$RET
	# language of errors
        db_get guifi-proxy3/language
        language=$RET
	# hd size of cache
        db_get guifi-proxy3/hd
        hd=$RET
	# ram size of cache
        db_get guifi-proxy3/ram
        ram=$RET


	# Force logrotate
	/usr/sbin/logrotate -f /etc/logrotate.d/guifi-proxy3
	/bin/touch /var/log/guifi-proxy3/guifi-proxy3.log

	/bin/echo "Loading special version Guifi.net ";
	## if exist guifi.conf delete
	if [ -e /etc/squid3/guifi.conf ]
	then
		/bin/rm /etc/squid3/guifi.conf
	fi
	## add var in /etc/guifi-proxy3/config.sh
	/bin/echo "base_url='$base_url'" >> /etc/guifi-proxy3/config.sh
	/bin/echo "node='$node'" >> /etc/guifi-proxy3/config.sh
	/bin/echo "ldap_main='$ldap_main'" >> /etc/guifi-proxy3/config.sh
	/bin/echo "ldap_backup='$ldap_backup'" >> /etc/guifi-proxy3/config.sh
	/bin/echo "realm='$proxy_name'" >> /etc/guifi-proxy3/config.sh
	/bin/echo "manager='$email'" >> /etc/guifi-proxy3/config.sh
	/bin/echo "language='$language'" >> /etc/guifi-proxy3/config.sh
	/bin/echo "cache_size='$hd'" >> /etc/guifi-proxy3/config.sh
	/bin/echo "cache_mem='$ram'" >> /etc/guifi-proxy3/config.sh
	## delete include custom.conf
	FILE="/etc/squid3/squid.conf"
       /bin/grep -Ev 'custom.conf' "$FILE" > "$FILE.tmp"
        /bin/grep -Ev 'guifi' "$FILE" > "$FILE.tmp"
        /bin/mv "$FILE.tmp" $FILE
        ## include config file custom.conf and guifi.conf in squid.conf
        /bin/echo "include /etc/squid3/custom.conf" > /tmp/squid.conf && /bin/echo "include /etc/squid3/guifi.conf" >> /tmp/squid.conf && /bin/cat /etc/squid3/squid.conf >> /tmp/squid.conf && /bin/rm /etc/squid3/squid.conf && /bin/mv /tmp/squid.conf /etc/squid3/squid.conf
	# delete old config in ldap.conf
        FILE="/etc/ldap/ldap.conf"
	/bin/grep -Ev 'TLS_REQCERT never' "$FILE" > "$FILE.tmp"
        /bin/mv "$FILE.tmp" $FILE
	# add REQCERT in  /etc/ldap/ldap.conf
	/bin/echo "TLS_REQCERT never" >>/etc/ldap/ldap.conf
	# first files.
	/bin/echo "" > /etc/squid3/custom.conf
	/bin/echo "" > /etc/squid3/guifi.conf
	# stop squid3
        invoke-rc.d squid3 stop
	# /usr/sbin/service squid3 stop
	# remove old cache memory
	/bin/rm -rf /var/spool/squid3/*
        # create installation control file
        /bin/touch /tmp/guifi-proxy3.crontrol
	# generate new guifi.conf in /etc/squid3/guifi.conf
	/usr/share/guifi-proxy3/guifi-proxy3.sh
        # new cache squid
        /usr/sbin/squid3 -z
        # remove instalation control file
        /bin/rm /tmp/guifi-proxy3.crontrol
	# the end
	exit 0;
	;;

	*)
	/bin/echo "postinst called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
