Document: guifi-proxy3
Title: Debian guifi-proxy3 Manual
Author: <insert document author here>
Abstract: This manual describes what guifi-proxy3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/guifi-proxy3/guifi-proxy3.sgml.gz

Format: postscript
Files: /usr/share/doc/guifi-proxy3/guifi-proxy3.ps.gz

Format: text
Files: /usr/share/doc/guifi-proxy3/guifi-proxy3.text.gz

Format: HTML
Index: /usr/share/doc/guifi-proxy3/html/index.html
Files: /usr/share/doc/guifi-proxy3/html/*.html
