#! /bin/sh
#
# $Id$ 
#

set -e

configfile='/etc/guifi-proxy3/config.sh';
tmpfile=`/bin/tempfile -m 644`;

case $1 in
	configure|reconfigure)

	. /usr/share/debconf/confmodule
	db_version 2.0 || [ $? -lt 30 ]

	db_get guifi-proxy3/baseurl
	base_url=$RET
	db_get guifi-proxy3/node
	node=$RET
	db_get guifi-proxy3/forcefetch
	forcefetch=$RET


	/bin/cat << EOT > $tmpfile

#!/bin/sh
#
# Script at /usr/share/guifi-proxy3
#
# Server base url ex: http://www.guifi.net
base_url='$base_url';
# Node ID
node=$node;

EOT

	/usr/bin/ucf --three-way --debconf-ok $tmpfile $configfile
	/bin/rm $tmpfile

	if [ $forcefetch ]
	then
		echo "Fetching passwd file.";
		if [ -x /usr/share/guifi-proxy3/guifi-proxy3.sh ]; then echo "..."; /usr/share/guifi-proxy3/guifi-proxy3.sh; fi
	fi
	# Force logrotate
	touch /var/log/guifi-proxy3/guifi-proxy3.log
	/usr/sbin/logrotate -f /etc/logrotate.d/guifi-proxy3

        if [ -e "/etc/squid3/squid.conf" ]; then
		echo "Saving a copy of the current squid.conf ........ ...... squid.conf.backup.initial";
                /bin/mv /etc/squid3/squid.conf /etc/squid3/squid.conf.backup.initial
        fi
	echo "Loading special version Guifi.net ";
        /bin/mv /tmp/squid.conf /etc/squid3/squid.conf
	echo "Starting the Squid proxy server ...... .......";
	/etc/init.d/squid3 start
	echo "Enjoy it !";
	exit 0
	;;

	*)
		echo "postinst called with unknown argument \`$1'" 1>&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
