#!/bin/bash
#
# $Id$
#

set -e

configfile='/etc/guifi-proxy3/config.sh';
tmpfile=`/bin/tempfile -m 644`;

case $1 in
	configure|reconfigure)

	. /usr/share/debconf/confmodule
	db_version 2.0 || [ $? -lt 30 ]

	db_get guifi-proxy3/baseurl
	base_url=$RET
	db_get guifi-proxy3/node
	node=$RET
	db_get guifi-proxy3/forcefetch
	forcefetch=$RET
        ## include name of server proxy in /etc/squid3/squid.conf
	db_get guifi-proxy3/proxy_name
	proxy_name=$RET
	# admin email
	db_get guifi-proxy3/email
        email=$RET
        db_get guifi-proxy3/language
        language=$RET
        db_get guifi-proxy3/hd
        hd=$RET
        db_get guifi-proxy3/ram
        ram=$RET


/bin/cat << EOT > $tmpfile
# Script at /usr/share/guifi-proxy3
# Server base url ex: http://www.guifi.net
base_url='$base_url';
# Node ID
node=$node;
EOT
	/usr/bin/ucf --three-way --debconf-ok $tmpfile $configfile
	/bin/rm $tmpfile

	if [ $forcefetch ]
	then
		echo "Fetching passwd file.";
		if [ -x /usr/share/guifi-proxy3/guifi-proxy3.sh ]; then echo "..."; /usr/share/guifi-proxy3/guifi-proxy3.sh; fi
	fi
	# Force logrotate
	touch /var/log/guifi-proxy3/guifi-proxy3.log
	/usr/sbin/logrotate -f /etc/logrotate.d/guifi-proxy3


	echo "Loading special version Guifi.net ";
	## if exist guifi.conf delete
	if [ -e /etc/squid3/guifi.conf ]
	then
		/bin/rm /etc/squid3/guifi.conf
	fi
	# copy default configuration of guifi.conf
	/bin/cp /usr/share/guifi-proxy3/guifi.example.conf /etc/squid3/guifi.conf
	## add special file of guifi
        echo "cache_mem $ram MB" >> /etc/squid3/guifi.conf
        echo "cache_dir ufs /var/spool/squid3 $hd 32 512" >> /etc/squid3/guifi.conf
	echo "auth_param basic realm $proxy_name Squid proxy-caching web server" >> /etc/squid3/guifi.conf
	echo "cache_mgr $email" >> /etc/squid3/guifi.conf
	echo "error_directory /usr/share/squid3/errors/$language" >> /etc/squid3/guifi.conf
	## delete include custom.conf
	FILE="/etc/squid3/squid.conf"
        grep -Ev 'custom.conf' "$FILE" > "$FILE.tmp"
        grep -Ev 'guifi' "$FILE" > "$FILE.tmp"
        mv "$FILE.tmp" $FILE
        ## include config file custom.conf and guifi.conf in squid.conf
        /bin/echo "include /etc/squid3/custom.conf" > /tmp/squid.conf && /bin/echo "include /etc/squid3/guifi.conf" >> /tmp/squid.conf && /bin/cat /etc/squid3/squid.conf >> /tmp/squid.conf && /bin/rm /etc/squid3/squid.conf && /bin/mv /tmp/squid.conf /etc/squid3/squid.conf
	# reload squid3 
	/usr/sbin/invoke-rc.d squid3 reload
	# magic ;)
	echo "Enjoy it";
	exit 0;
	;;

	*)
	echo "postinst called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
