#!/bin/bash
#
# $Id$ 
#

set -e

configfile='/etc/guifi-proxy3/config.sh';
tmpfile=`/bin/tempfile -m 644`;

case $1 in
	configure|reconfigure)

	. /usr/share/debconf/confmodule
	db_version 2.0 || [ $? -lt 30 ]

	db_get guifi-proxy3/baseurl
	base_url=$RET
	db_get guifi-proxy3/node
	node=$RET
	db_get guifi-proxy3/forcefetch
	forcefetch=$RET
        ## include name of server proxy in /etc/squid3/squid.conf
	db_get guifi-proxy3/proxy_name
	proxy_name=$RET
	## include hosts lan allow with administrator of squid server
	db_get guifi-proxy3/allow_host
	allow_host=$RET

	/bin/cat << EOT > $tmpfile

# Script at /usr/share/guifi-proxy3
#
# Server base url ex: http://www.guifi.net
base_url='$base_url';
# Node ID
node=$node;

EOT

	/usr/bin/ucf --three-way --debconf-ok $tmpfile $configfile
	/bin/rm $tmpfile

	if [ $forcefetch ]
	then
		echo "Fetching passwd file.";
		if [ -x /usr/share/guifi-proxy3/guifi-proxy3.sh ]; then echo "..."; /usr/share/guifi-proxy3/guifi-proxy3.sh; fi
	fi
	# Force logrotate
	touch /var/log/guifi-proxy3/guifi-proxy3.log
	/usr/sbin/logrotate -f /etc/logrotate.d/guifi-proxy3


	echo "Loading special version Guifi.net ";
	## if exist delete include /foo/guifi.conf
	##
        FILE="/etc/squid3/squid.conf"
        grep -Ev 'guifi' "$FILE" > "$FILE.tmp"
        mv "$FILE.tmp" $FILE
        ## if exist delele old configuration
        FILE="/etc/squid3/guifi.conf"
        grep -Ev 'realm' "$FILE" > "$FILE.tmp"
        mv "$FILE.tmp" $FILE
	## add special file of guifi
	echo "auth_param basic realm $proxy_name Squid proxy-caching web server" >> /etc/squid3/guifi.conf
	## include hosts lan allow with administrator of squid server
	echo "http_access deny to_privada_deny" >> /etc/squid3/guifi.conf
        if [ $allow_host ]; then
                echo "acl to_privada_allow dst $allow_host " >> /etc/squid3/guifi.conf
                echo "http_access allow to_privada_allow " >> /etc/squid3/guifi.conf
        fi
	## la finalitat d'aquesta linia es afegir el include al principi del fitxer de configuració. 
	##    afegir include a un fitxer tmp				vomitar el contingut de squid.conf al tmp            eliminiar el squid.conf original    moure el tmp al lloc que li toca
	/bin/echo "include /etc/squid3/guifi.conf" > /tmp/squid.conf && /bin/cat /etc/squid3/squid.conf >> /tmp/squid.conf && /bin/rm /etc/squid3/squid.conf && /bin/mv /tmp/squid.conf /etc/squid3/squid.conf
	invoke-rc.d squid3 reload
	echo "Enjoy it";
	exit 0;
	;;

	*)
	echo "postinst called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
