#!/bin/sh
#
# $Id$
#

set -e

grepconf2 () {
        w="     " # space tab
        sq=/etc/squid/squid.conf
        # sed is cool.
        res=`sed -ne '
                s/^'$1'['"$w"']\+[^'"$w"']\+['"$w"']\+\([^'"$w"']\+\).*$/\1/p;
                t end;
                d;
                :end q' < $sq`
        [ -n "$res" ] || res=$2
        echo "$res"
}

case $1 in
	configure|reconfigure)
		. /usr/share/debconf/confmodule
		db_version 2.0 || [ $? -lt 30 ]
		#
		db_get guifi-proxy3/baseurl
		cache_dir=`grepconf2 cache_dir /var/spool/squid`
		base_url=$RET
		db_get guifi-proxy3/node
		node=$RET
		#first ldap server
		db_get guifi-proxy3/ldap_main
		ldap_main=$RET
		# second and backup ldap server
		db_get guifi-proxy3/ldap_backup
		ldap_backup=$RET
		## include name of server proxy in /etc/squid/squid.conf
		db_get guifi-proxy3/proxy_name
		proxy_name=$RET
		# admin email
		db_get guifi-proxy3/email
		email=$RET
		# language of errors
		db_get guifi-proxy3/language
		language=$RET
		# hd size of cache
		db_get guifi-proxy3/hd
		hd=$RET
		# ram size of cache
		db_get guifi-proxy3/ram
		ram=$RET



		# Force logrotate
		/usr/sbin/logrotate -f /etc/logrotate.d/guifi-proxy3
		/bin/touch /var/log/guifi-proxy3/guifi-proxy3.log

		/bin/echo "Loading special version Guifi.net ";
		## if exist guifi.conf delete
		if [ -e /etc/squid/guifi.conf ]
		then
			/bin/rm /etc/squid/guifi.conf
		fi
		## add var in /etc/guifi-proxy3/config.sh
		/bin/echo "base_url='$base_url'" >> /etc/guifi-proxy3/config.sh
		/bin/echo "node='$node'" >> /etc/guifi-proxy3/config.sh
		/bin/echo "ldap_main='$ldap_main'" >> /etc/guifi-proxy3/config.sh
		/bin/echo "ldap_backup='$ldap_backup'" >> /etc/guifi-proxy3/config.sh
		/bin/echo "realm='$proxy_name'" >> /etc/guifi-proxy3/config.sh
		/bin/echo "manager='$email'" >> /etc/guifi-proxy3/config.sh
		/bin/echo "language='$language'" >> /etc/guifi-proxy3/config.sh
		/bin/echo "cache_size='$hd'" >> /etc/guifi-proxy3/config.sh
		/bin/echo "cache_mem='$ram'" >> /etc/guifi-proxy3/config.sh
		## delete include custom.conf
		FILE="/etc/squid/squid.conf"
		/bin/grep -Ev 'custom.conf' "$FILE" > "$FILE.tmp"
		/bin/grep -Ev 'guifi' "$FILE" > "$FILE.tmp"
		/bin/mv "$FILE.tmp" $FILE
		## include config file custom.conf and guifi.conf in squid.conf
		/bin/echo "include /etc/squid/custom.conf" > /tmp/squid.conf && /bin/echo "include /etc/squid/guifi.conf" >> /tmp/squid.conf && /bin/cat /etc/squid/squid.conf >> /tmp/squid.conf && /bin/rm /etc/squid/squid.conf && /bin/mv /tmp/squid.conf /etc/squid/squid.conf
		# delete old config in ldap.conf
		FILE="/etc/ldap/ldap.conf"
		/bin/grep -Ev 'TLS_REQCERT never' "$FILE" > "$FILE.tmp"
		/bin/mv "$FILE.tmp" $FILE
		# add REQCERT in  /etc/ldap/ldap.conf
		/bin/echo "TLS_REQCERT never" >>/etc/ldap/ldap.conf
		# Create files.
		/bin/touch /etc/squid/custom.conf
		/bin/touch  /etc/squid/guifi.conf
                # generate new guifi.conf in /etc/squid/guifi.conf
                /usr/share/guifi-proxy3/guifi-proxy3.sh

		/usr/sbin/service squid stop
		if [ -f /var/spool/squid_old ]
		then
			/bin/rm /var/spool/squid_old
		fi
		/bin/mv /var/spool/squid /var/spool/squid_old
		/bin/mkdir /var/spool/squid
		/bin/chown proxy:proxy /var/spool/squid
                /bin/rm -Rf /var/spool/squid_old
		/usr/sbin/squid -z
                /bin/rm -Rf /var/spool/squid_old
		/bin/echo "Please run:";
		/bin/echo "/usr/sbin/invoke-rc.d squid start";
		/bin/echo "Or wait cronjob to start it. (5 minutes max)";
                /bin/echo "Enjoy it";

		exit 0;
		;;
	*)

       /bin/echo "postinst called with unknown argument \`$1'" 1>&2
       exit 1
       ;;

esac

exit 0
