#!/bin/bash
#
/bin/echo ""
/bin/echo "`date +%y-%m-%d___%k:%M`-----------------------------------------------------------------------------------"
/usr/sbin/service squid stop
if [ -f /var/spool/squid_old ]
then
    /bin/rm /var/spool/squid_old
fi
/bin/mv /var/spool/squid /var/spool/squid_old
/bin/mkdir /var/spool/squid
/bin/chown proxy:proxy /var/spool/squid
/usr/sbin/squid squid -z
/usr/sbin/service squid start
/bin/rm -Rf /var/spool/squid_old
#fi

